### ISSUE TITLE
Add Wizard Mob

### ISSUE THREAD

**Issue by K-Mistele** [amistele/seeker-of-the-sword#33]
- [x] Wizard mob should be able to damage player if player is within a three-block radius. 
- [x] Weak damage output, low health. 
- [x] There should be some way of indicating that it is the wizard that is attacking (character color should flash?)
- [x] ~~Wizard should only spawn in true seeker difficulty~~
- [x] Should only spawn in dungeons
- [x] Should spawn an imp every four turns

**Comment by amistele** [comment]
Not five block radius, needs to be proportional to world dim.... 5 is way too big on a 16x16 map

**Comment by K-Mistele** [comment]
Updates:
- Wizard has a weak ranged attack
- Now, update mobs so that necromancers summon weak cursed shadow mobs when able
- currently only appear if you enter `mob test` as your name on the items and mobs  enhancement branch
- also, there is now a way to hardcode mob locations upon their creation.

**Comment by K-Mistele** [comment]
TODO: 
- make pull request
- document methods and new parameters
